services:
  db:
    image: postgres:15-alpine
    container_name: saas_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      # Exposes the container's port 5432 to your local machine's port 5432
      - "5432:5432"

volumes:
  postgres_data: